name: 'Line messaging api'

on: [ push, pull_request ]

jobs:
    run:
        name: PHP ${{ matrix.php-versions }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [ '7.2' ]
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP with PECL extension
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: php_sockets, sodium

            -   name: Install dependencies
                uses: php-actions/composer@v5
                with:
                    php-version: ${{ matrix.php-versions }}
                    dev: yes

            -   uses: php-actions/phpunit@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    bootstrap: vendor/autoload.php
                    configuration: phpunit.xml.dist
                    args: --coverage-text
